---
title: "Downloadable Dyadic Foreign Policy Similarity Data Sets"
---

Users are free to recreate the entire universe of foreign policy similarity
scores using the functions available in these data, though that would be a 
tedious use of time. Toward that end, I have the following data sets available
for download in either the [`qs2` framework](https://github.com/qsbase/qs2) 
(`.qs`) or the native R serialized data frame (`.rds`). 

| **Data Set Description** | **Data Source** | **Link** |
|:-----------------------------|:-------------------:|:--------:|
| Signorino and Ritter's (1999) *S* (unweighted) | ATOP Alliances | ([.qs][1], [.rds][2]) |
| Signorino and Ritter's (1999) *S* (weighted) | ATOP Alliances | ([.qs][3], [.rds][4])  |
| Benati and Capurri's (2026) *A* (unweighted) | ATOP Alliances | ([.qs][5], [.rds][6])  |
| Benati and Capurri's (2026) *A* (weighted) | ATOP Alliances | ([.qs][7], [.rds][8])  |
| Cohen's kappa [κ] and Scott's pi [π]   | ATOP Alliances | ([.qs][9], [.rds][10])  |
| Kendall's Tau-b [τb] | ATOP Alliances | ([.qs][11], [.rds][12]) |
| Benati and Capurri's (2026) *A* (unweighted) | UN Resolutions | ([.qs][13], [.rds][14]) |
| Cohen's kappa [κ] and Scott's pi [π]   | UN Resolutions | ([.qs][15], [.rds][16])  |

All data sets are directed dyad-year data all-inclusive of the Correlates of War 
state system. The temporal domain of the alliance data is 1816-2018. The temporal 
domain of the UN voting data is 1946-2022, though be mindful of 
[the gap year in 1964](https://ask.un.org/faq/268504).

[`{peacesciencer}`](https://svmiller.com/peacesciencer)'s [`add_fpsim()`](https://svmiller.com/peacesciencer/reference/add_fpsim.html)
function makes use of a subset of the measures available for download. You can 
[download that here](https://svmiller.com/fpsim/data/FPSIM.rds), if you'd like.
The [`download_extdata()`](https://svmiller.com/peacesciencer/reference/download_extdata.html)
function in [`{peacesciencer}`](https://svmiller.com/peacesciencer) will download
this and stick it in that package's `extdata` directory in order for the 
[`add_fpsim()`](https://svmiller.com/peacesciencer/reference/add_fpsim.html) to
work.

## A Brief Description of Terminology

I am a product of my time, which privileges shorter, punchier, and somewhat 
oblique variable names in lieu of the more verbose column names with underscores
that have proliferated with the rise of IDEs and chatbots. Toward that end,
let me underscore my terminology in these column names and how one can see 
something like `sallybwa` to mean "Signorino and Ritter's (1999) S using binary
alliance data, weighted by CINC scores and using absolute distances" and understand
that `pvotev` is a dead giveaway that the data are Scott's (1955) pi for UN
General Assembly votes on their original, valued scale.

### `s/k/p/a`

The first letter of the variable always communicates what the foreign policy 
similarity measure is. `s` is [Signorino and Ritter's (1999)](https://doi.org/10.1111/0020-8833.00113) 
S. `k` is Cohen's ([1960](https://journals.sagepub.com/doi/abs/10.1177/001316446002000104), 
[1968](https://psycnet.apa.org/doi/10.1037/h0026256)) (k)appa. `p` is [Scott's (1955)](https://www.jstor.org/stable/2746450) (p)i. 
`a` is [Benati and Capurri's (2026)](https://link.springer.com/article/10.1007/s11135-026-02814-x) 
Alignment Index (A), which is basically a chance-corrected S score.


### `ally`/`vote`

These communicate the information from which a measure of foreign policy 
similarity is constructed. `ally` refers to alliance data generated by the ATOP 
project, covering 1816-2018. `vote` refers to UN voting data, covering all 
UN decisions from 1946 to 2022. Note that these four letters always follow the 
first letter of the variable (which always communicates what the type of measure 
is).

### `u` vs. `w`

These are unique to Signorino and Ritter's (1999) S measure, which I generate 
only for the alliance data. `u` means the measure of S is unweighted by anything 
and that each alliance tie is equally important in a given dyadic pairing. 
`w` means the data are weighted by the target state's CINC score in a dyadic 
pairing. I maintain [this is generally ill-advised]([here](https://svmiller.com/blog/2026/06/alliances-weighting-foreign-policy-similarity/), 
certainly for anything outside the 19th century, but it did reflect common 
practice in quantitative IR studies for the longest time. Because Benati and
Capurri (2026) are offering what amounts to a chance-corrected S measure, I
have weighted and unweighted estimates of A as well.

### `b` vs. `v`

This concerns measures of foreign policy similarity using alliance ties. Standard 
practice for the longest time suggested you could construct an ordinal measure 
of an alliance tie on a scale of 0 to 3. 0 would mean no alliance at all. 1 
would be an entente. 2 would be neutrality and/or a non-aggression pact. 3 would 
be a defense pact. In this reading, the alliance data are fundamentally "valued" 
(`v`). Discussion on my blog ([here](https://svmiller.com/blog/2026/06/alliances-weighting-foreign-policy-similarity/) 
and [here](https://svmiller.com/blog/2021/11/calculate-tau-b-alliances-in-r/)) and 
[on `{peacesciencer}`'s  documentation](https://svmiller.com/peacesciencer/reference/add_fpsim.html) 
underscore why I've never liked this convention and think it drastically misreads 
what the alliance data actually communicate, but this was the convention I 
remember learning. If you elect to use the alliance data for a measure of
foreign policy similarity (i.e. you need the pre-WW2 reach), I would strongly
encourage you to use the measure that treats the alliance as strictly binary 
(`b`) (where 0 = no alliance contract and 1 = some form of an alliance contract).
Note that the UN voting data are always valued, where 1 = yes, 2 = abstain, 3 =
nay.

### `a` vs. `s`

This concerns Signorino and Ritter's S and Benati and Capurri's A  because both 
measure a conceptual "distance". `a` means the distances are  "absolute" distances 
where `s` means the distances are squared. I forget off the top of my head 
whether Signorino and Ritter's S measure was intended to be done with absolute 
distances or whether software packages of the time that included this measure 
(i.e. EUGene) only offered absolute distances and never belabored this choice to 
the user. The choice is fundamentally arbitrary though squared distances are 
much more commonly used in most other types of distance and association metrics.
Please be advised again that this should not be confused with the `a` or `s` that
might appear as the first character of the column.

## A More Formal Codebook

| **Variable** | **Meaning** |
|:----------:|:-------------------------------------------------------------------------------|
| `aallyvus` | *A* using (v)alued, (u)nweighted alliance (ally) data with (s)quared distances |
| `aallyvua` | *A* using (v)alued, (u)nweighted alliance (ally) data with (a)bsolute distances |
| `aallybus` | *A* using (b)inary, (u)nweighted alliance (ally) data with (s)quared distances |
| `aallybua` | *A* using (b)inary, (u)nweighted alliance (ally) data with (a)bsolute distances |
| `aallyvws` | *A* using (v)alued, (w)eighted alliance (ally) data with (s)quared distances |
| `aallyvwa` | *A* using (v)alued, (w)eighted alliance (ally) data with (a)bsolute distances |
| `aallybws` | *A* using (b)inary, (w)eighted alliance (ally) data with (s)quared distances |
| `aallybwa` | *A* using (b)inary, (w)eighted alliance (ally) data with (a)bsolute distances |
| `pallyv` | Scott's (p)i (v)alued alliance (ally) data |
| `pallyb` | Scott's (p)i (b)inary alliance (ally) data |
| `kallyv` | Cohen's (k)appa using (v)alued alliance (ally) data |
| `kallyb` | Cohen's (k)appa using (b)inary alliance (ally) data |
| `sallyvus` | *S* using (v)alued, (u)nweighted alliance (ally) data with (s)quared distances |
| `sallyvua` | *S* using (v)alued, (u)nweighted alliance (ally) data with (a)bsolute distances |
| `sallybus` | *S* using (b)inary, (u)nweighted alliance (ally) data with (s)quared distances |
| `sallybua` | *S* using (b)inary, (u)nweighted alliance (ally) data with (a)bsolute distances |
| `sallyvws` | *S* using (v)alued, (w)eighted alliance (ally) data with (s)quared distances |
| `sallyvwa` | *S* using (v)alued, (w)eighted alliance (ally) data with (a)bsolute distances |
| `sallybws` | *S* using (b)inary, (w)eighted alliance (ally) data with (s)quared distances |
| `sallybwa` | *S* using (b)inary, (w)eighted alliance (ally) data with (a)bsolute distances |
| `taub` | Kendall's Tau-b on valued alliance data (a legacy measure) |
| `avoteva` | *A* using (v)alued UN voting (vote) data, (a)bsolute distances |
| `avotevs` | *A* using (v)alued UN voting (vote) data, (s)quared distances |
| `pvotev` | Scott's (p)i using (v)alued UN voting (vote) data |
| `kvotev` | Cohen's (k)appa using (v)alued UN voting (vote) data  |


[1]: https://svmiller.com/fpsim/data/fpsim-alliances-s-unweighted.qs
[2]: https://svmiller.com/fpsim/data/fpsim-alliances-s-unweighted.rds
[3]: https://svmiller.com/fpsim/data/fpsim-alliances-s-weighted.qs
[4]: https://svmiller.com/fpsim/data/fpsim-alliances-s-weighted.rds
[5]: https://svmiller.com/fpsim/data/fpsim-alliances-a-unweighted.qs
[6]: https://svmiller.com/fpsim/data/fpsim-alliances-a-unweighted.rds
[7]: https://svmiller.com/fpsim/data/fpsim-alliances-a-weighted.qs
[8]: https://svmiller.com/fpsim/data/fpsim-alliances-a-weighted.rds
[9]: https://github.com/svmiller/fpsim/raw/refs/heads/main/docs/data/fpsim-alliances-pk.qs
[10]: https://github.com/svmiller/fpsim/raw/refs/heads/main/docs/data/fpsim-alliances-pk.rds
[11]: https://github.com/svmiller/fpsim/raw/refs/heads/main/docs/data/fpsim-alliances-taub.qs
[12]: https://github.com/svmiller/fpsim/raw/refs/heads/main/docs/data/fpsim-alliances-taub.rds
[13]: https://github.com/svmiller/fpsim/raw/refs/heads/main/docs/data/fpsim-votes-a.qs
[14]: https://github.com/svmiller/fpsim/raw/refs/heads/main/docs/data/fpsim-votes-a.rds
[15]: https://github.com/svmiller/fpsim/raw/refs/heads/main/docs/data/fpsim-votes-pk.qs
[16]: https://github.com/svmiller/fpsim/raw/refs/heads/main/docs/data/fpsim-votes-pk.rds
